apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hypershift-rlfy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hypershift-rlfy
    app.kubernetes.io/part-of: hypershift
  name: hypershift-rlfy
spec:
  ports:
  - port: 16
    targetPort: 16
  selector:
    app.kubernetes.io/instance: hypershift-rlfy
status:
  loadBalancer: {}
